apiVersion: v1
kind: ConfigMap
data:
  __files:
  mappings/catchall.json: "{\r\n   \"name\": \"catchall\",\r\n   \"request\": {\r\n      \"method\":
    \"GET\",\r\n      \"urlPattern\": \".*\",\r\n      \"basicAuth\": {\r\n         \"username\":
    \"test\",\r\n         \"password\": \"test\"\r\n     }\r\n   },\r\n   \"response\":
    {\r\n      \"body\": \"I'm backoffice\",\r\n      \"headers\": {\r\n         \"Content-Type\":
    \"application/json;charset=UTF-8\"\r\n      },\r\n      \"status\": 200\r\n   }\r\n}\r\n"
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backoffice
  name: backoffice-cm0
