apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --volumes configMap
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backoffice
  name: backoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backoffice
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --volumes configMap
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: backoffice
    spec:
      containers:
        - args:
            - --verbose
            - --global-response-templating
            - --max-template-cache-entries
            - "0"
          image: wiremock/wiremock:latest
          name: backoffice
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /home/wiremock
              name: backoffice-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: backoffice-cm0
          name: backoffice-cm0
status: {}
