apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice
  labels:
    type: wiremock
spec:
  replicas: 1
  selector:
    matchLabels:
      type: wiremock
  template:
    metadata:
      labels:
        type: wiremock         
    spec:
      containers:
      - name: wiremock
        image: wiremock/wiremock:3.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: wiremock-mapping
          mountPath: /home/wiremock/mappings
      volumes:
        - name: wiremock-mapping
          configMap:
            name: wiremock-mapping

---
apiVersion: v1
kind: Service
metadata:
  name: wiremock-svc
  labels:
    type: wiremock
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    type: wiremock
  type: LoadBalancer
---
apiVersion: v1
data:
  catchall.json: "{\r\n   \"name\": \"catchall\",\r\n   \"request\": {\r\n      \"method\":
    \"GET\",\r\n      \"urlPattern\": \".*\",\r\n      \"basicAuth\": {\r\n         \"username\":
    \"test\",\r\n         \"password\": \"test\"\r\n     }\r\n   },\r\n   \"response\":
    {\r\n      \"body\": \"I'm backoffice\",\r\n      \"headers\": {\r\n         \"Content-Type\":
    \"application/json;charset=UTF-8\"\r\n      },\r\n      \"status\": 200\r\n   }\r\n}\r\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: wiremock-mapping