apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-exam-center.yaml --volumes configMap
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: exam-liege
  name: exam-liege
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: exam-liege
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-exam-center.yaml --volumes configMap
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: exam-liege
    spec:
      containers:
        - args:
            - --verbose
            - --global-response-templating
            - --max-template-cache-entries
            - "0"
          image: wiremock/wiremock:3.5.4
          name: exam-liege
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /home/wiremock/__files
              name: wiremock-files
          volumeMounts:
            - mountPath: /home/wiremock/mappings
              name: wiremock-mappings
      restartPolicy: Always
      volumes:
        - name: wiremock-mappings
          configMap:
            name: exam-liege-cm0
status: {}
