apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-autosecurite-center.yaml --volumes configMap
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: autosecurite-liege
  name: autosecurite-liege
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 8080
  selector:
    io.kompose.service: autosecurite-liege
